name: kpi_schedule
description: Diploma project made by Vladyslav Lopata

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^3.0.1
  bloc: ^7.2.1
  chopper: ^4.0.1
  chopper_generator: ^4.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  freezed_annotation: ^0.15.0
  get_it: ^7.2.0
  injectable: ^1.5.0
  intl: ^0.17.0
  json_annotation: ^4.3.0
  shared_preferences: ^2.0.8

dev_dependencies:
  auto_route_generator: ^3.0.1
  build_runner: ^2.1.1
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^0.15.0+1
  injectable_generator: ^1.4.1
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true

  assets:
    - data/schedule.json
